### PR TITLE
Designator class loggable too

### PR DESCRIPTION
**Pull request by gheorghelisca**
- for chemlab  applications we need to log generic designators.

### CODE REVIEW

**Comment by fairlight1337** [comment]
Darn, the dependency towards `sem-map-utils` was actually unintended; `cram_beliefstate` was supposed to have as few dependencies as possible, including not depending on the semantic map packages.

Seems like I didn't pay attention when I introduced the check for existence of the `sem-map-utils` package [here](https://github.com/cram2/cram_beliefstate/blob/master/cram_beliefstate/src/beliefstate.lisp#L381) and use the very same package explicitly right after.

Sorry about that; I'd still be in favor of resolving this dependency if possible.

**Comment by gheorghelisca** [comment]
@fairlight1337 this pull request is about extending some checks on the classes of the designators which are about to be logged. in principle in chemlab demo i need to log ```LOCATION```, ```OBJECT```, ```ACTION``` and the generic class ```DESIGNATOR``` too. i extended ```cram_beliefstate``` to support this feature and i would like to see if this feature doesn't break possible assumptions i am not aware of.

**Comment by fairlight1337** [comment]
I'll give it a shot and will let you know; if nothing breaks I'll merge it directly :).

**Comment by fairlight1337** [comment]
@gheorghelisca, the message type I was talking about earlier can be found in the [designator_integration_msgs](https://github.com/code-iai/iai_common_msgs/blob/master/designator_integration_msgs/msg/Designator.msg#L6) package. Basically, each designator integration message has a `type` field that signifies the type of designator its transporting. These currently are `OBJECT`, `ACTION`, `LOCATION`, and `HUMAN`. Per default, this `int32` field resorts to `0` which is equivalent to `OBJECT`. I guess this is why the message transport worked for you without introducing a new type.

I'll go over the rest of the PR now.

**Comment by fairlight1337** [comment]
Okay, that's shorter than I initially expected :). Looks like it should work out of the box. I'll check it out and compile and try it. Before I do that, could you pull in the [latest changes](https://github.com/cram2/cram_beliefstate/commit/e7ccf9f902739b615f4697d1ac616d965ae143f3) from <kbd>cram_beliefstate/master</kbd> that remove the explicit dependency on `cram_semantic_map_utils` again and push it into your pull request? Thanks!

**Comment by fairlight1337** [comment]
I merged it in and tried it out; look good to me, merging it.

**Comment by gheorghelisca** [comment]
thanks a lot @fairlight1337 ! i think the [latest changes](https://github.com/cram2/cram_beliefstate/commit/e7ccf9f902739b615f4697d1ac616d965ae143f3) are already in the ```master```, so for me works very nice.

**Pull request merged**
