### PR TITLE
Fix sem map utils dependency

### PR DESCRIPTION
**Pull request by fairlight1337**
Hey @gheorghelisca, thanks for the fix in https://github.com/cram2/cram_beliefstate/pull/4. I saw all of this too late and didn't see my brain fart from before (as documented in your original pull request [here](https://github.com/cram2/cram_beliefstate/pull/5#issuecomment-238366405)).

So the idea was to keep the dependency towards `cram_semantic_map_utils` out of `cram_beliefstate`; sorry I failed to do so with that other change.

I found a way to read the symbol's value anyway while first checking whether the package is present. This PR works for me and should do the trick, while removing again the dependency on sem-map-utils. Sorry for retracting your change with that.

### CODE REVIEW

**Comment by gheorghelisca** [comment]
@fairlight1337 absolutely no problem ... the less dependencies the better :) ... could you please remove the dependencies from the ```package.xml``` and from the ```cram-beliefstate.asd``` too so that the pull request is more complete? :)

**Comment by fairlight1337** [comment]
I did, but apparently it was too late for me ;). Didn't commit or push the changes. Will do in a second :).

**Comment by gaya-** [comment]
@fairlight1337  this function returns a failure if the package is not loaded. Could you please make sure you catch the error and ignore it? It's an `SB-KERNEL:SIMPLE-PACKAGE-ERROR`

**Comment by fairlight1337** [comment]
Right, thanks; forgot a `when`. Addressed in this PR: https://github.com/cram2/cram_beliefstate/pull/7

**Pull request merged**
